# frozen_string_literal: true

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
    - 'db/**/*'

Metrics/ClassLength:
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/**/*'
