# frozen_string_literal: true

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'

Metrics/LineLength:
  Max: 150
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false
