# frozen_string_literal: true

url = 'https://www.womenshealthmag.com/life/a22500573/questions-to-ask-to-get-to-know-someone/'
source = Source.create!(url: url)

questions = [
  'What’s your favorite way to spend a day off?',
  'What type of music are you into?',
  'What was the best vacation you ever took and why?',
  'Where’s the next place on your travel bucket list and why?',
  'What are your hobbies, and how did you get into them?',
  'What was your favorite age growing up?',
  'Was the last thing you read?',
  'Would you say you’re more of an extrovert or an introvert?',
  "What's your favorite ice cream topping?",
  'What was the last TV show you binge-watched?',
  'Are you into podcasts or do you only listen to music?',
  'Do you have a favorite holiday? Why or why not?',
  'If you could only eat one food for the rest of your life, what would it be?',
  'Do you like going to the movies or prefer watching at home?',
  'What’s your go-to guilty pleasure?',
  'In the summer, would you rather go to the beach or go camping?',
  'What’s your favorite quote from a TV show/movie/book?',
  'How old were you when you had your first celebrity crush, and who was it?',
  "What's one thing that can instantly make your day better?",
  'Do you have any pet peeves?',
  'Which meal is your favorite: breakfast, lunch, or dinner?',
  'What song always gets you out on the dance floor?',
  'When you were a kid, did you eat the crusts on your sandwich or not?',
  'What activity instantly calms you?',
  'Ideally, how would you spend your birthday?',
  'What do you do on your commute to/from work?',
  'Do you have a favorite type of exercise?',
  "What's your favorite season and why?",
  "What's the best joke you've ever heard?",
  "What's the phone app you use most?",
  'Would you rather cook or order in?',
  'Have your ever disliked something and then changed your mind?',
  "What's your favorite board game?",
  'How do you take your coffee?',
  "What's your most prized possession and why?",
  "Is there any product that you couldn't live without?",
  'If you could have any exotic animal as a pet, which would it be?',
  "What would be the first thing you'd do if you won the lottery?",
  'What’s your favorite thing about your current job?',
  'What annoys you most?',
  'What’s the career highlight you’re most proud of?',
  'Do you think you’ll stay in your current gig awhile? Why or why not?',
  'What type of role do you want to take on after this one?',
  'Are you more of a "work to live" or a "live to work" type of person?',
  'Does your job make you feel happy and fulfilled? Why or why not?',
  'How would your 10-year-old self react to what you do now?',
  'What do you remember most about your first job?',
  'How old were you when you started working?',
  'What’s the worst job you’ve ever had?',
  'What originally got you interested in your current field of work?',
  'Have you ever had a side hustle or considered having one?',
  'What’s your favorite part of the workday?',
  'What’s the best career decision you’ve ever made?',
  'What’s the worst career decision you’ve ever made?',
  'Do you consider yourself good at networking?',
  'What career advice would you give to your younger self?',
  'Do you believe in having a "five-year plan"?',
  'How do you separate your work life from your home life?',
  "When will you know you've \"made it\"?",
  'Are you looking forward to retiring, or do you plan to work as long as possible?',
  'Have you ever had "imposter syndrome"?',
  'What do you think about workaholics?',
  'What qualities do you look for in a boss?',
  'Do you have a professional mentor? If not, do you want one?',
  'Do you have a work best friend?',
  'Are you into after-work happy hours?',
  'How do you motivate yourself in your career?',
  "What's the best career advice you've ever heard?",
  "What's the worst career advice you've ever received?",
  'When you started your current job, what most surprised you?',
  'How do you pick yourself back up after making a mistake at work?',
  'How do you deal with work stress?',
  'What energizes you about your career?',
  "What's one work-related thing you want to accomplish in the next year?",
  'Who has had the biggest impact on your career choice?',
  'What does your family think of your career?',
  "What's the best thing you've learned in your current position?",
  'If you could do it all over again, would you pursue the same career? Why or why not?',
  'If you had only one sense (hearing, touch, sight, etc.), which would you want?',
  'What is your definition of success?',
  'What makes you feel at peace?',
  'What are you most proud of in the last year?',
  'What makes you feel most accomplished?',
  'Who do you admire most in the world?',
  'Would you rather make more money doing a job you hate or less doing one you love?',
  'Which of your personality traits are you most proud of?',
  'What’s the first thing you look for in a partner and/or friend?',
  'How has your perspective on the world changed over time?',
  'Do you live by any piece of advice or motto?',
  'How can someone earn your trust?',
  'How can someone lose your trust?',
  'Would you rather someone be honest and hurt your feelings or lie to protect them?',
  'If you could snap your fingers and instantly make the world better, what would you do?',
  'Do you believe in astrology? Why or why not?',
  'Have you ever lost a friend? If so, what happened?',
  'If you could only teach one thing to your (future) child, what would it be?',
  'What’s the scariest thing you’ve ever done, and why did you do it?',
  'Do you believe in second chances?',
  'Where do you get your news?',
  'What is your biggest irrational fear?',
  'Are you active on social media, or do you prefer to be more private?',
  'Do you volunteer at all?',
  'Are you an organ donor, and how did you come to that decision?',
  'Do you believe you should do one thing a day that scares you?',
  'If you see a puddle on the ground, do you walk around it or over it?',
  'If you could have a super power, what would it be?',
  'If you could go back to anytime in history, where would you go?',
  'If you came back in your next life as an animal, what animal would you be?',
  'If you got to name a new country, how would you decide what to call it?',
  'What would be the title of your memoir?',
  'Do you hit the snooze button or wake up immediately?',
  'What’s the first thing you do in the morning?',
  'What’s the last thing you do at night?',
  'Do you believe in any conspiracy theories (no judgement)?',
  'Do you think iced coffee should only be consumed in the summer or all year round?',
  'Would you rather be covered in fur or covered in scales?',
  'What’s your idea of a perfect date (yes, of the calendar year)?',
  'What’s the most unusual place you’ve fallen asleep?',
  'At a party, where can someone find you?',
  'Do you wash your legs in the shower?',
  'Who would play you in the movie of your life?',
  'When making a PB&J sandwich, do you put on the peanut butter or jelly first?',
  'Do you have any allergies?',
  'Do you trust your own memory? Why or why not?',
  'Which fictional character do you relate to most?',
  'What, if anything, would make you walk out in the middle of a movie?',
  "What's your most controversial opinion about something mundane?",
  'Do you "stan" any celebrities?',
  "What's your go-to midnight snack?",
  'What was your all-time favorite Halloween costume?',
  "What's the weirdest thing you do when you're alone?",
  'Do you have any recurring dreams?',
  "What's the silliest argument you've ever been in?",
  "What's the worst argument you've ever been in?",
  "What's your opinion on modern art?",
  'If you could choose how to die, would you? If so, what would you choose?',
  "What's the most ridiculous outfit you've ever worn?",
  'What was the first thing you wanted to be when you grew up?',
  'If you could own a mythical creature (unicorn, phoenix, etc.), which one would you pick?',
  "What's your least favorite place in the world?",
  'Would you rather have your dishes or clothes be magically clean?',
  'If you could change anything about yourself, would you? If so, what and why?'
]

questions.each do |question|
  Question.create!(source: source, query: question)
end
