# frozen_string_literal: true

class AddWouldYouQuestions < ActiveRecord::Migration[7.0]
  def up
    source = Source.create!(url: 'https://conversationstartersworld.com/would-you-rather-questions/')
    questions = [
      "Would you rather the aliens that make first contact be robotic or organic?",
      "Would you rather lose the ability to read or lose the ability to speak?",
      "Would you rather have a golden voice or a silver tongue?",
      "Would you rather be covered in fur or covered in scales?",
      "Would you rather be in jail for a year or lose a year off your life?",
      "Would you rather always be 10 minutes late or always be 20 minutes early?",
      "Would you rather have one real get out of jail free card or a key that opens any door?",
      "Would you rather know the history of every object you touched or be able to talk to animals?",
      "Would you rather be married to a 10 with a bad personality or a 6 with an amazing personality?",
      "Would you rather be able to talk to land animals, animals that fly, or animals that live under the water?",
      "Would you rather have all traffic lights you approach be green or never have to stand in line again?",
      "Would you rather spend the rest of your life with a sailboat as your home or an RV as your home?",
      "Would you rather give up all drinks except for water or give up eating anything that was cooked in an oven?",
      "Would you rather be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?",
      "Would you rather have an easy job working for someone else or work for yourself but work incredibly hard?",
      "Would you rather be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?",
      "Would you rather go back to age 5 with everything you know now or know now everything your future self will learn?",
      "Would you rather be able to control animals (but not humans) with your mind or control electronics with your mind?",
      "Would you rather have unlimited international first-class tickets or never have to pay for food at restaurants?",
      "Would you rather see what was behind every closed door or be able to guess the combination of every safe on the first try?",
      "Would you rather be an average person in the present or a king of a large country 2500 years ago?",
      "Would you rather be able to dodge anything no matter how fast it's moving or be able to ask any three questions and have them answered accurately?",
      "Would you rather be forced to dance every time you heard music or be forced to sing along to any song you heard?",
      "Would you rather have all your clothes fit perfectly or have the most comfortable pillow, blankets, and sheets in existence?",
      "Would you rather 5% of the population have telepathy, or 5% of the population have telekinesis? You are not part of the 5% that has telepathy or telekinesis.",
      "Would you rather be an unimportant character in the last movie you saw or an unimportant character in the last book you read?",
      "Would you rather move to a new city or town every week or never be able to leave the city or town you were born in?",
      "Would you rather be completely insane and know that you are insane or completely insane and believe you are sane?",
      "Would you rather travel the world for a year on a shoestring budget or stay in only one country for a year but live in luxury?",
      "Would you rather suddenly be elected a senator or suddenly become a CEO of a major company? (You won't have any more knowledge about how to do either job than you do right now.)",
      "Would you rather live in virtual reality where you are all powerful or live in the real world and be able to go anywhere but not be able to interact with anyone or anything?",
      "Would you rather have whatever you are thinking to appear above your head for everyone to see or have absolutely everything you do live streamed for anyone to see?",
      "Would you rather humans discover a signal from intelligent life from another planet or figure out how to extend human life for another 100 years?",
      "Would you rather be only able to watch the few movies with a Rotten Tomatoes score of 95-100% or only be able to watch the majority of movies with a Rotten Tomatoes score of 94% and lower?",
      "Would you rather wake up as a new random person every year and have full control of them for the whole year or once a week spend a day inside a stranger without having any control of them?",
      "Would you rather know how above or below average you are at everything or know how above or below average people are at one skill/talent just by looking at them?",
      "Would you rather live until you are 200 but look like you are 200 the whole time even though you are healthy or look like you are 25 all the way until you die at age 65?",
      "Would you rather be able to slow down time by 10% or jump three times as high as you can now?",
      "Would you rather be born again in the same country or a different one of your choosing?",
      "Would you rather be forced to go 10 mph under the speed limit or 10 mph over the speed limit? You can still get speeding tickets.",
      "Would you rather take an all expenses paid dream vacation every year for a month or have the job of your dreams?",
      "Would you rather give up using a phone or tablet forever or give up having any salt in food?",
      "Would you rather get a post card every day from a stranger in a different country or a 10 minute call with anyone in the world you choose once a year?",
      "Would you rather have a successful podcast or a successful YouTube channel?",
      "Would you rather watch a movie with no snacks or drink or have whatever you want but the movie volume is always just a little to quiet or a little too loud?",
      "Would you rather always live 10 miles from where you were born or never be able to settle down in one place for more than a year?",
      "Would you rather work hard for a boss that has high expectations but values you as a person and employee or work much less for a boss that couldn't care less?",
      "Would you rather never be able to drink water again or only be able to drink water?",
      "Would you rather be a successful artist or a successful business owner?",
      "Would you rather reroll your stats (intelligence, strength, constitution, etc) knowing that they could come out much worse or much better or just stay the same as you are now?",
      "Would you rather be a reverse centaur or a reverse mermaid/merman?",
      "Would you rather your only mode of transportation be a donkey or a giraffe?",
      "Would you rather only be to use a fork (no spoon) or only be able to use a spoon (no fork)?",
      "Would you rather every shirt you ever wear be kind of itchy or only be able to use 1 ply toilet paper?",
      "Would you rather have edible spaghetti hair that regrows every night or sweat (not sweet) maple syrup?",
      "Would you rather have to read aloud every word you read or sing everything you say out loud?",
      "Would you rather wear a wedding dress/tuxedo every single day or wear a bathing suit every single day?",
      "Would you rather be unable to move your body every time it rains or not be able to stop moving while the sun is out?",
      "Would you rather have all dogs try to attack you when they see you or all birds try to attack you when they see you?",
      "Would you rather be compelled to high five everyone you meet or be compelled to give wedgies to anyone in a green shirt?",
      "Would you rather have skin that changes color based on your emotions or tattoos appear all over your body depicting what you did yesterday?",
      "Would you rather randomly time travel +/- 20 years every time you fart or teleport to a different place on earth (on land, not water) every time you sneeze?",
      "Would you rather there be a perpetual water balloon war going on in your city/town or a perpetual food fight?",
      "Would you rather have to fart loudly every time you have a serious conversation or have to burp after every kiss?",
      "Would you rather become twice as strong when both of your fingers are stuck in your ears or crawl twice as fast as you can run?",
      "Would you rather have everything you draw become real but be permanently terrible at drawing or be able to fly but only as fast as you can walk?",
      "Would you rather thirty butterflies instantly appear from nowhere every time you sneeze or one very angry squirrel appear from nowhere every time you cough?",
      "Would you rather eat a sandwich made from 4 ingredients in your fridge chosen at random or eat a sandwich made by a group of your friends from 4 ingredients in your fridge?",
      "Would you rather everyone be required to wear identical silver jumpsuits or any time two people meet and are wearing an identical article of clothing they must fight to the death?",
      "Would you rather be inside a portable toilet when it's pushed over or die three weeks earlier than you normally would have?",
      "Would you rather trees scream occasionally for no reason or spiders be big enough and smart enough to open doors?",
      "Would you rather every third thought you have be out loud or never be alone no matter what you are doing?",
      "Would you rather everyone listen to music and podcasts without headphones or everyone be unreasonably proud of their flatulence and body odor?",
      "Would you rather have the ability to mute people at will or pause people for five seconds at a time, but only once an hour?",
      "Would you rather be able to control lights with your mind or actually be able to throw your voice?",
      "Would you rather only be able to wear clown shoes or not be able to wear any shoes?",
      "Would you rather be the head of a company or the head of a cult?",
      "Would you rather jump into a gigantic snow cone with just your bathing suit in winter or roll down a relatively large hill wearing a helmet, 5 jackets, and 10 pairs of pants in summer?",
      "Would you rather wear only uncomfortable shoes whenever you go outside or comfy shoes always (even to bed)?",
      "Would you rather get a surprise wet willy from a random stranger every day or a surprise wedgie from a random stranger every day?",
      "Would you rather whatever house you live in to have one strong smell of your choosing for the rest of your life or wake up to your house smell to change randomly every day?",
      "Would you rather be a famous director or a famous actor?",
      "Would you rather be a practicing doctor or a medical researcher?",
      "Would you rather live in a cave or live in a tree house?",
      "Which do you cheer for in fantasy movies and books, dwarves or elves?",
      "Would you rather be able to control fire or water?",
      "Would you rather live without the internet or live without AC and heating?",
      "Would you rather be able to teleport anywhere or be able to read minds?",
      "Would you rather be unable to use search engines or unable to use social media?",
      "Would you rather be beautiful/handsome but stupid or intelligent but ugly?",
      "Would you rather be balding but fit or overweight with a full head of hair?",
      "Would you rather never be able to eat meat or never be able to eat vegetables?",
      "Would you rather have a completely automated home or a self-driving car?",
      "Would you rather be an amazing painter or a brilliant mathematician?",
      "Would you rather be famous but ridiculed or be just a normal person?",
      "Would you rather have a flying carpet or a car that can drive underwater?",
      "Would you rather never be stuck in traffic again or never get another cold?",
      "Would you rather have a bottomless box of Legos or a bottomless gas tank?",
      "Would you rather be forced to eat only spicy food or only incredibly bland food?",
      "Would you rather be a bowling champion or a curling champion?",
      "Would you rather be fantastic at riding horses or amazing at driving dirt bikes?",
      "Would you rather never be able to wear pants or never be able to wear shorts?",
      "Would you rather live the next 10 years of your life in China or Russia?",
      "Would you rather live on the beach or in a cabin in the woods?",
      "Would you rather be lost in a bad part of town or lost in the forest?",
      "Would you rather have a horrible short-term memory or a horrible long-term memory?",
      "Would you rather be completely invisible for one day or be able to fly for one day?",
      "Would you rather never be able to use a touchscreen or never be able to use a keyboard and mouse?",
      "Would you rather have unlimited sushi for life or unlimited tacos for life? (both are amazingly delicious and can be any type of sushi/taco you want)",
      "Would you rather get one free round trip international plane ticket every year or be able to fly domestic anytime for free?",
      "Would you rather be able to be free from junk mail or free from email spam for the rest of your life?",
      "Would you rather give up bathing for a month or give up the internet for a month?",
      "Would you rather give up watching TV/movies for a year or give up playing games for a year?",
      "Would you rather never be able to drink sodas like coke again or only be able to drink sodas and nothing else?",
      "Would you rather have amazingly fast typing/texting speed or be able to read ridiculously fast?",
      "Would you rather live under a sky with no stars at night or live under a sky with no clouds during the day?",
      "Would you rather have free Wi-Fi wherever you go or be able to drink unlimited free coffee at any coffee shop?",
      "Would you rather take amazing selfies, but all of your other pictures are horrible or take breathtaking photographs of anything but yourself?",
      "Would you rather never get a paper cut again or never get something stuck in your teeth again?",
      "Would you rather never have another embarrassing fall in public or never feel the need to pass gas in public again?",
      "Would you rather lose your best friend or all of your friends except for your best friend?",
      "Would you rather it never stops snowing (the snow never piles up) or never stops raining (the rain never causes floods)?",
      "Would you rather never be able to leave your own country or never be able to fly in an airplane?",
      "Would you rather never have a toilet clog on you again or never have the power go out again?",
      "Would you rather earbuds and headphones never sit right on / in your ears or have all music either slightly too quiet or slightly too loud?",
      "Would you rather be the best in the world at climbing trees or the best in the world at jumping rope?",
      "Would you rather never run out of battery power for whatever phone and tablet you own or always have free Wi-Fi wherever you go?",
      "Would you rather never have to clean a bathroom again or never have to do dishes again?",
      "Would you rather eat an egg with a half-formed chicken inside or eat ten cooked grasshoppers?",
      "Would you rather only wear one color each day or have to wear seven colors each day?",
      "Would you rather eat rice with every meal and never be able to eat bread or eat bread with every meal and never be able to eat rice?",
      "Would you rather travel the world for a year all expenses paid or have $40,000 to spend on whatever you want?",
      "Would you rather be able to go to any theme park in the world for free for the rest of your life or eat for free at any drive-through restaurant for the rest of your life?",
      "Would you rather be the absolute best at something that no one takes seriously or be well above average but not anywhere near the best at something well respected?",
      "Would you rather it be impossible for you to be woken up for 11 straight hours every day, but you wake up feeling amazing, or you can be woken up normally but never feel totally rested?",
      "Would you rather have everything in your house perfectly organized by a professional or have a professional event company throw the best party you've ever been to, in your honor?",
      "Would you rather have unlimited amounts of any material you want to build a house, but you have to build the house all by yourself or have a famed architect design and build you a modest house?",
      "Would you rather never sweat again but not be more prone to heat stroke or never feel cold again but cold still physically affects you (i.e., you can freeze to death)?",
      "Would you rather accept help or just take care of things on your own?",
      "Would you rather live in a nice house in a boring town or a rough house in an exciting town?",
      "Would you rather be fluent in legalese or fluent in French?",
      "Would you rather be able to speed read or speak at an incredible speed?",
      "Would you rather remember everyone's name you've ever met or know how to mix every cocktail ever made?",
      "Would you rather be given a top tier gaming PC or a top tier Apple computer? Both are the same price.",
      "Would you rather type faster or dance better?",
      "Would you rather have infrared vision that you can turn on/off at will or 20x normal telescopic vision?",
      "Would you rather be a great success in your personal life or your professional life?",
      "Would you rather sleep on the floor with a pillow and blanket or sleep on a bed without a pillow or blanket?",
      "Would you rather eat something savory or sweet?",
      "Would you rather read a hardback book or a paperback book?",
      "Would you rather take a weeklong hiking / camping vacation or a weeklong cruise?",
      "Would you rather owe someone a lot of money or owe them a big favor?",
      "Would you rather hang out with your family or your friends?",
      "Would you rather star in a movie or a TV series?",
      "Would you rather have a new expensive pair of shoes or an expensive pair of sunglasses?",
      "Would you rather perform in a circus or act in plays?",
      "Would you rather be lost in the woods of a mountain for a year or stranded on a tropical island for a year?",
      "Would you rather ask for help with a difficult task or figure out how to do it yourself?",
      "Would you rather be able to drink or eat as much as you want without weight or health consequences?",
      "Would you rather only need to sleep three hours a day without being tired / hurting your health or only need to eat once a week without being hungry / hurting your health?",
      "Would you rather be YouTube famous or TV famous?",
      "Would you rather have your whole house completely carpeted or completely tiled?",
      "Would you rather be a drum prodigy or a bass guitar prodigy?",
      "Would you rather have a huge event wedding or a small one and use the money you saved to go on an amazing honeymoon?",
      "Would you rather super sensitive taste or super sensitive hearing?",
      "Would you rather have constantly dry eyes or a constant runny nose?",
      "Would you rather never lose your phone again or never lose your keys again?",
      "Would you rather have out of control body hair or a strong, pungent body odor?",
      "Would you rather be unable to have kids or only be able to conceive quintuplets?",
      "Would you rather clean rest stop toilets or work in a slaughterhouse for a living?",
      "Would you rather lose all your money and valuables or all the pictures you have ever taken?",
      "Would you rather find your true love or a suitcase with five million dollars inside?",
      "Would you rather not be able to see any colors or have mild but constant tinnitus (ringing in the ears)?",
      "Would you rather have chapped lips that never heal or terrible dandruff that can't be treated?",
      "Would you rather live without hot water for showers/baths or live without a washing machine?",
      "Would you rather be alone for the rest of your life or always be surrounded by annoying people?",
      "Would you rather be locked in a room that is constantly dark for a week or a room that is constantly bright for a week?",
      "Would you rather accidentally be responsible for the death of a child or accidentally be responsible for the deaths of three adults?",
      "Would you rather know when you are going to die or how you are going to die? (You can't change the time or method of your death.)",
      "Would you rather have everything you eat be too salty or not salty enough no matter how much salt you add?",
      "Would you rather never have to work again or never have to sleep again (you won't feel tired or suffer negative health effects)?",
      "Would you rather never use social media sites/apps again or never watch another movie or TV show?",
      "Would you rather be fluent in all languages and never be able to travel or be able to travel anywhere for a year but never be able to learn a word of a different language?",
      "Would you rather have everything on your phone right now (browsing history, photos, etc.) made public to anyone who searches your name or never use a cell phone again?",
      "Would you rather be an amazing artist but not be able to see any of the art you created or be an amazing musician but not be able to hear any of the music you create?",
      "Would you rather have everyone laugh at your jokes but not find anyone else's jokes funny or have no one laugh at your jokes but you still find other people's jokes funny?",
      "Would you rather wake up in the middle of an unknown desert or wake up in a rowboat on an unknown body of water?",
      "Would you rather be in debt for $100,000 or never be able to make more than $3,500 a month?",
      "Would you rather have the police hunting you for a murder you didn't commit or a psychopathic clown hunting you?",
      "Would you rather be constantly tired no matter how much you sleep or constantly hungry no matter how much you eat?",
      "Would you rather be so afraid of heights that you can't go to the second floor of a building or be so afraid of the sun that you can only leave the house on rainy days?",
      "Would you rather get tipsy from just one sip of alcohol and ridiculously drunk from just one alcoholic drink or never get drunk no matter how much alcohol you drank?",
      "Would you rather get $2,000 a month until you die or $500,000 right now?",
      "Would you rather lose the three possessions you hold most dear or lose everything else except for those three possessions?",
      "Would you rather get a suitcase that has $10,000 or a suitcase that has a 50/50 chance to be $1,000 or $50,000?",
      "Would you rather help one person a lot who really needs it or make one hundred people's lives a little bit better?",
      "Would you rather eat a live worm or a dead worm?",
      "Would you rather be completely offline for the next year or lose a finger or toe of your choice?",
      "Would you rather instantly get to your goal weight and get buff / in shape or instantly grow 4 inches?",
      "Would you rather have a leaky faucet that can't be fixed / replaced or a running toilet that can't be fixed / replaced?",
      "Would you rather have a non-venomous spider infestation or a mouse infestation in your house?",
      "Would you rather cheat at a game and win or lose but know you gave it your best shot?",
      "Would you rather stay in one of those sensory deprivation tanks for a day or in a room designed for overstimulation for a day?",
      "Would you rather swallow five live worms or one live cockroach?",
      "Would you rather be feared by all or loved by all?",
      "Would you rather sell all of your possessions or sell one of your organs?",
      "Would you rather be infamous in history books or be forgotten after your death?",
      "Would you rather be reincarnated as a fly or just cease to exist after you die?",
      "Would you rather never get angry or never be envious?",
      "Would you rather have a horribly corrupt government or no government?",
      "Would you rather be held in high regard by your parents or your friends?",
      "Would you rather be poor but help people or become incredibly rich by hurting people?",
      "Would you rather humans go to the moon again or go to mars?",
      "Would you rather know the uncomfortable truth of the world or believe a comforting lie?",
      "Would you rather die in 20 years with no regrets or die in 50 years with many regrets?",
      "Would you rather be transported permanently 500 years into the future or 500 years into the past?",
      "Would you rather donate your body to science or donate your organs to people who need them?",
      "Would you rather be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die?",
      "Would you rather go to jail for 4 years for something you didn't do or get away with something horrible you did but always live in fear of being caught?",
      "Would you rather live in the wilderness far from civilization with no human contact or live on the streets of a city as a homeless person?",
      "Would you rather live your entire life in a virtual reality where all your wishes are granted or just in the normal real world?",
      "Would you rather have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?",
      "Would you rather lose all of your memories from birth to now or lose your ability to make new long-term memories?",
      "Would you rather always be able to see 5 minutes into the future or always be able to see 100 years into the future?",
      "Would you rather be forced to kill one innocent person or five people who committed minor crimes?",
      "Would you rather work very hard at a rewarding job or hardly have to work at a job that isn't rewarding?",
      "Would you rather have a criminal justice system that actually works and is fair or an administrative branch that is free of corruption?",
      "Would you rather have real political power but be relatively poor or be ridiculously rich and have no political power?",
      "Would you rather have the power to gently nudge anyone's decisions or have complete puppet master control of five people?",
      "Would you rather live in a utopia as a normal person or in a dystopia but you are the supreme ruler?",
      "Would you rather snitch on your best friend for a crime they committed or go to jail for the crime they committed?",
      "Would you rather be born again in a totally different life or born again with all the knowledge you have now?",
      "Would you rather all conspiracy theories be true or live in a world where no leaders really know what they are doing?",
      "Would you rather know all the mysteries of the universe or know every outcome of every choice you make?",
      "Would you rather spend two years with your soul mate only to have them die and you never love again or spend your life with someone nice you settled for?",
      "Would you rather have all corporations know all of your computer usage or the government know all of your computer usage?",
      "Would you rather inherit 20 million dollars when you turn 18 or spend the time earning 50 million dollars through your hard work?",
      "Would you rather fight for a cause you believe in, but doubt will succeed or fight for a cause that you only partially believe in but have a high chance of your cause succeeding?",
      "Would you rather be famous for inventing a deadly new weapon or invent something that helps the world but someone else gets all the credit for inventing it?",
      "Would you rather eat at the same restaurant you usually do or a new restaurant that just opened?",
      "Would you rather be given a new BMW now or be given a truly epic $2 million dollar mausoleum after you die?",
      "Would you rather remember every single thing that happened in the last 10 years of your life or know what you are going to do for the next 10 months but not be able to change it?",
      "Would you rather stop everyone in the world except for yourself from getting any illness or stop yourself from ever getting any illness while the rest of the world stays as it is?",
      "Would you rather be a human brain in a robot body or have your brain enhanced with a computer in your human body?",
      "Would you rather solve problems in the world or just live your life without worrying about the problems in the world?",
      "Would you rather be the most popular person in your school / workplace or the smartest / most talented?",
      "Would you rather live as a hermit for ten years or live the rest of your life in a country chosen completely at random?",
      "Would you rather genuinely and unironically love every movie you see or song you hear despite the quality of the movie or song and what others think of it?",
      "Would you rather there be absolutely nothing after you die or wander the earth as a ghost unable to interact with people or things and be alone for eternity?",
      "Would you rather take a pill that gives you 100 more healthy years or a pill that makes you 10x more intelligent than you currently are?",
      "Would you rather know the secrets of everyone on Earth or know everything we don't know about the universe except for the Earth?",
      "Would you rather everyone in the world be kinder and more compassionate or more intelligent?",
      "Would you rather be watched at all times by a strict but benevolent AI where there is no crime or poverty or live in a place with no laws, government, or leaders?",
      "Would you rather live in a world run by children aged 5 to 12 or a world run by one supremely powerful person randomly selected by lottery every 15 years?",
      "Would you rather your shirts be always two sizes too big or one size too small?",
      "Would you rather find five dollars on the ground or find all your missing socks?",
      "Would you rather have one nipple or two belly buttons?",
      "Would you rather eat a ketchup sandwich or a Siracha sandwich?",
      "Would you rather use a push lawnmower with a bar that is far too high or far too low?",
      "Would you rather eat a box of dry spaghetti noodles or two cups of uncooked rice?",
      "Would you rather eat a spoonful of wasabi or a spoonful of extremely spicy hot sauce?",
      "Would you rather have hands that kept growing as you got older or feet that kept growing as you got older?",
      "Would you rather not be able to open any closed doors (locked or unlocked) or not be able to close any open doors?",
      "Would you rather have plants grow at 20 times their normal rate when you are near or for people and animals to stop aging when you are near them?",
      "Would you rather always feel like someone is following you, but no one is, or always feel like someone is watching you, even though no one is?",
      "Would you rather live in a house with see-through walls in a city or in the same see-through house but in the middle of a forest far from civilization?",
      "Would you rather have every cat or dog that gets lost end up at your house or everyone's clothes that they forget in the dryer get teleported to your house?",
      "Would you rather blink twice the normal rate or not be able to blink for 5 minutes but then have to close your eyes for 10 seconds every 5 minutes?",
      "Would you rather all plants scream when you cut them / pick their fruit or animals beg for their lives before they are killed?",
      "Would you rather everything you dream each night come true when you wake up or everything a randomly chosen person dreams each night come true when they wake up?",
      "Would you rather have someone secretly give you LSD on a random day and time once every 6 months or have everyone in the world all take LSD at the same time once every 5 years?",
      "Would you rather all electrical devices mysteriously stop working (possibly forever) or the governments of the world are only run by people going through puberty?",
      "Would you rather fight an angry 15ft anaconda to the death or 15 angry koalas to the death?",
      "Would you rather live in a house filled with mannequins dressed as clowns or a house filled with porcelain dolls?",
      "Would you rather have the olfactory senses of a dog or see more colors in the electromagnetic spectrum like a mantis shrimp?",
      "Would you rather live in a world of smooth curves with no sharp angles or a word of only sharp angles and no curves? Assuming humans keep the shape they are now.",
      "Would you rather be forced to speak in a single different accent not of your choosing forever or speak in a random different accent whenever you wake up for one year?",
      "Would you rather have all your meals prepared for you but you don't get to choose the dish or sleep eight hours every night but you don't get to choose your bedtime?",
      "Would you rather be a human swiss army knife like Inspector Gadget or be the richest person in the World?",
      "Would you rather have your friends never bail on plans they make or be able to make shoot paper into a trash bin no matter how difficult the shot?",
      "Would you rather be able to see through walls but not windows or stay the same as you are now?",
      "Would you rather always know exactly what time it is or always know which direction you are facing?",
      "Would you rather have the ability to change your hair color at will or the color of your clothes at will?",
      "Would you rather have all drugs be legalized or dueling between consenting adults be legalized?"
    ]

    questions.each do |question|
      Question.create!(source:, query: question, would_you: true)
    end
  end

  def down; end
end
